from __future__ import annotations

from .models import ENERGY_MODES, INTENTS, PROJECT_FORMATS


SLOP_BRIEF_RESPONSE_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        "title": {"type": "STRING"},
        "slug": {"type": "STRING"},
        "format": {"type": "STRING", "enum": list(PROJECT_FORMATS)},
        "chaos": {"type": "INTEGER", "minimum": 1, "maximum": 10},
        "output_dir": {"type": "STRING"},
        "intent": {
            "type": "STRING",
            "enum": list(INTENTS),
            "description": "The practical/experiential intent, such as funny toy, educational explainer, useful utility, game, reference tool, creative instrument, or simulation.",
        },
        "energy_mode": {
            "type": "STRING",
            "enum": list(ENERGY_MODES),
            "description": "The tonal energy shaping the interaction, such as frantic, cozy, competitive, tactical, mischievous, ceremonial, mechanical, elegant, meditative, or practical.",
        },
        "artifact_metaphor": {"type": "STRING"},
        "concept": {"type": "STRING"},
        "primary_signal": {
            "type": "STRING",
            "description": "The dominant transferable force, pattern, or mechanic used for the core interaction.",
        },
        "supporting_signals": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "minItems": 1,
            "maxItems": 4,
        },
        "surprise_hook": {"type": "STRING"},
        "core_interaction": {"type": "STRING"},
        "suggested_stack": {"type": "STRING"},
        "build_constraints": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "minItems": 3,
            "maxItems": 5,
        },
        "done_criteria": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "minItems": 3,
            "maxItems": 5,
        },
    },
    "required": [
        "title",
        "slug",
        "format",
        "chaos",
        "output_dir",
        "intent",
        "energy_mode",
        "artifact_metaphor",
        "concept",
        "primary_signal",
        "supporting_signals",
        "surprise_hook",
        "core_interaction",
        "suggested_stack",
        "build_constraints",
        "done_criteria",
    ],
    "propertyOrdering": [
        "title",
        "slug",
        "format",
        "chaos",
        "output_dir",
        "intent",
        "energy_mode",
        "artifact_metaphor",
        "concept",
        "primary_signal",
        "supporting_signals",
        "surprise_hook",
        "core_interaction",
        "suggested_stack",
        "build_constraints",
        "done_criteria",
    ],
}
