from __future__ import annotations

from .models import PROJECT_FORMATS


SLOP_BRIEF_RESPONSE_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        "title": {"type": "STRING"},
        "slug": {"type": "STRING"},
        "format": {"type": "STRING", "enum": list(PROJECT_FORMATS)},
        "chaos": {"type": "INTEGER", "minimum": 1, "maximum": 10},
        "output_dir": {"type": "STRING"},
        "one_line_pitch": {"type": "STRING"},
        "concept": {"type": "STRING"},
        "source_influences": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "minItems": 3,
            "maxItems": 8,
        },
        "core_interaction": {"type": "STRING"},
        "visual_direction": {"type": "STRING"},
        "suggested_stack": {"type": "STRING"},
        "build_constraints": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "minItems": 4,
            "maxItems": 7,
        },
        "expected_files": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "minItems": 2,
            "maxItems": 8,
        },
        "done_criteria": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "minItems": 4,
            "maxItems": 7,
        },
        "entropy_digest": {"type": "STRING"},
    },
    "required": [
        "title",
        "slug",
        "format",
        "chaos",
        "output_dir",
        "one_line_pitch",
        "concept",
        "source_influences",
        "core_interaction",
        "visual_direction",
        "suggested_stack",
        "build_constraints",
        "expected_files",
        "done_criteria",
        "entropy_digest",
    ],
    "propertyOrdering": [
        "title",
        "slug",
        "format",
        "chaos",
        "output_dir",
        "one_line_pitch",
        "concept",
        "source_influences",
        "core_interaction",
        "visual_direction",
        "suggested_stack",
        "build_constraints",
        "expected_files",
        "done_criteria",
        "entropy_digest",
    ],
}
